POST http://localhost:3000/api/course/create
Content-Type: application/json

{
    "name": "Discrete Mathematics",
    "code": "CSE220",
    "department": "Computer Science",
    "faculty": "Martin Szoboslai"
}

###
GET http://localhost:3000/api/course/search

###
PUT http://localhost:3000/api/course/update/C001
Content-Type: application/json

{
    "name": "Basic",
    "code": "CSE110",
    "department": "Computer Science",
    "faculty": "Martin Luther King"
}

###
DELETE http://localhost:3000/api/course/delete/C001