POST http://localhost:3000/api/course/create
Content-Type: application/json

{
    "_id": "C001",
    "name": "Basic Programming Language",
    "code": "CSE110",
    "department": "Computer Science",
    "faculty": "Martin Luther King"
}

###
GET http://localhost:3000/api/course/search

###
PUT http://localhost:3000/api/course/update/61c80e08012cfa5fdbed01ae
Content-Type: application/json

{
    "_id": "C001",
    "name": "Basic Programming Language",
    "code": "CSE110",
    "department": "Computer Science",
    "faculty": "Martin Luther King"
}

###
DELETE http://localhost:3000/api/course/delete/C001