POST http://localhost:3000/api/course/create
Content-Type: application/json

{
    "name": "Analytic and Vector Geometry",
    "code": "MAT122",
    "department": "Mathematics and Natural Sciences",
    "faculty": "Khosh Mohammad"
}

###
GET http://localhost:3000/api/course/search

###
PUT http://localhost:3000/api/course/update/C001
Content-Type: application/json

{
    "name": "Basic",
    "code": "CSE110",
    "department": "Computer Science",
    "faculty": "Martin Luther King"
}

###
DELETE http://localhost:3000/api/course/delete/C001