POST http://localhost:3000/api/student/create
Content-Type: application/json

{
    "name": "Sanjana",
    "dob": "1996-07-11",
    "gender": "Female",
    "phone": "01433445666",
    "department": "CSE",
    "courses": ["61c995d18d32830c7a294be8"]
}

###
PATCH http://localhost:3000/api/student/addCourses/61c94b94e0f4e1363a923ba6
Content-Type: application/json

{
    "courses": ["CSE210"]
}

###
PATCH http://localhost:3000/api/student/removeCourse/61c94b94e0f4e1363a923ba6
Content-Type: application/json

{
    "courses": ["CSE270"]
}

###
GET http://localhost:3000/api/student/search/61c9961e8d32830c7a294bec

###
GET http://localhost:3000/api/student/search

###
PUT http://localhost:3000/api/student/update/61c9961e8d32830c7a294bec
Content-Type: application/json

{
    "name": "Sanjana",
    "dob": "1996-07-11",
    "gender": "Female",
    "phone": "01433445666",
    "department": "CSE",
    "courses": ["61c995d18d32830c7a294be8"]
}

###
DELETE http://localhost:3000/api/student/delete/61c9961e8d32830c7a294bec